version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientcheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u2a4o9cdpaik"
s3_prefix = "patientcheckout"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
